name: Automatic Release on Push to Main

on:
  push:
    branches:
      - main # Запускается только при пуше в ветку main

permissions:
  contents: write # Необходимо для создания тега и релиза

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Получаем всю историю, чтобы можно было найти предыдущие теги
          fetch-depth: 0

      - name: Get Version from userscript
        id: get_version
        # Ищем строку, содержащую "@version", извлекаем номер версии с помощью утилиты sed
        run: echo "VERSION=$(grep "@version" youtubespeedx.userscript.js | sed -n 's/.*@version\s*//p')" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        # Проверяем, существует ли уже тег для этой версии, чтобы избежать ошибок
        run: |
          if git rev-parse "v${{ steps.get_version.outputs.VERSION }}" >/dev/null 2>&1; then
            echo "Tag v${{ steps.get_version.outputs.VERSION }} already exists. Skipping release."
            exit 78 # Специальный код выхода для пропуска шагов
          fi

      - name: Extract Release Notes from CHANGELOG
        id: extract_notes
        run: |
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          # Используем awk для извлечения содержимого для конкретной версии.
          # Он начинает печать после нахождения строки с тегом текущей версии
          # и останавливается, когда находит следующий тег версии или конец файла.
          awk '/^## \['"$VERSION"'\]/{flag=1; next} /^## \[/{flag=0} flag' CHANGELOG.md > releasenotes.md
          
          # Проверяем, что файл не пустой, иначе версия в CHANGELOG.md не найдена.
          if [ ! -s releasenotes.md ]; then
            echo "Error: Release notes for version v${VERSION} not found in CHANGELOG.md."
            exit 1
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        # Этот шаг выполняется, только если тег не был найден на предыдущем шаге
        if: success()
        with:
          # Создаем тег и релиз с именем на основе извлеченной версии
          tag_name: "v${{ steps.get_version.outputs.VERSION }}"
          name: "Release v${{ steps.get_version.outputs.VERSION }}"
          # Автоматически извлекает описание из временного файла с заметками
          body_path: "releasenotes.md"
          # Прикрепляет указанный файл к релизу
          files: youtubespeedx.userscript.js
          token: ${{ secrets.GITHUB_TOKEN }}
